apiVersion: apps/v1
kind: Deployment
metadata:
  name: domgame-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: domgame-deployment
  template:
    metadata:
      labels:
        app: domgame-deployment
    spec:
      containers:
      - name: app
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        imagePullPolicy: Always