apiVersion: apps/v1
kind: Deployment
metadata:
  name: dominion-deployment
  labels:
    app: dominion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dominion
  template:
    metadata:
      labels:
        app: dominion
    spec:
      containers:
      - name: dominion
        image: dominion1:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: dominion-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: dominion
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001

