apiVersion: v1
kind: Service
metadata:
  name: dominion-app
  namespace: dominion
spec:
  ports:
  - port: 3001 # the port of the service
    protocol: TCP
    targetPort: 3001 # Should match EXPOSE port from dominion-app Dockerfile
    nodePort: 30001 # the port exposed on node 
  selector:
    app: dominion-app
  type: NodePort