name: Build and Deploy to Google CloudRun

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: ${{secrets.GKE_CLUSTER_NAME}}
  GKE_ZONE: ${{secrets.GKE_ZONE}}
  DEPLOYMENT_NAME: dominionstats-deployment
  IMAGE: dominionstats-image

jobs:
  setup-build-publish-deploy:
    name: Setup Build Publish Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Unit Tests
        run: |-
          npm install
          npm run test:unit

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          export_default_credentials: true

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
      
      - name: Build Docker Image
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" .
      
      - name: Publish Docker Image to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
      
      - name: Deploy Image to CloudRun
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: dominionstats-image
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:${{ github.sha }}

      - name: CloudRun Deploy Results
        run: curl "${{ steps.deploy.outputs.url }}"



